import { useEffect, useState } from "react";
import { api } from "./api.ts";
import { uiText } from "./i18n.tsx";

export function ConversationEvidence({ id }: { id: string }) {
  const [data, setData] = useState<Awaited<ReturnType<typeof api.conversationEvidence>>>();
  const [error, setError] = useState("");
  useEffect(() => { let active = true; setData(undefined); setError(""); void api.conversationEvidence(id).then(value => { if (active) setData(value); }).catch(e => { if (active) setError(String(e)); }); return () => { active = false; }; }, [id]);
  return <details className="mt-4 rounded border p-3 text-sm"><summary>{uiText("交付、反馈与执行记录")}</summary>
    {error ? <p role="alert">{error}</p> : !data ? <p>{uiText("加载中…")}</p> : <div className="mt-3 flex max-h-80 flex-col gap-3 overflow-auto">
      {!data.deliverables.length && !data.feedback.length && !data.contexts.length ? <p>{uiText("暂无记录")}</p> : null}
      {data.deliverables.map(item => <div key={item.key}><b>{item.key} · {item.description}</b><p>{item.status === "verified" ? uiText("已核验") : item.status === "produced" ? uiText("已生成") : uiText("待完成")}</p>{item.asset_id ? <a className="underline" href={`/v1/files/${item.asset_id}/content?download=1`}>{uiText("下载")}</a> : null}{item.evidence ? <p>{item.evidence}</p> : null}</div>)}
      {data.feedback.map(item => <p key={item.entry_id} className="whitespace-pre-wrap">{uiText("反馈")}: {item.text}</p>)}
      {data.contexts.map(item => <details key={item.runId}><summary>{item.modelId} · {item.modelInput.join(", ")}</summary><pre className="whitespace-pre-wrap break-all text-xs">{item.runId}{"\n"}{item.tools.join("\n")}</pre></details>)}
    </div>}
  </details>;
}

/** Original bytes are loaded by the client, never regenerated by the language model. */
export function ResourceQuote({ id }: { id: string }) {
  const [quote, setQuote] = useState<Awaited<ReturnType<typeof api.resourceQuote>>>();
  const [error, setError] = useState("");
  const [copied, setCopied] = useState(false);
  useEffect(() => {
    let active = true;
    setQuote(undefined); setError(""); setCopied(false);
    void api.resourceQuote(id).then(value => { if (active) setQuote(value); }).catch(e => { if (active) setError(String(e)); });
    return () => { active = false; };
  }, [id]);
  return <span className="my-2 block rounded-lg border bg-muted/30 p-3 not-italic" data-testid="resource-quote">
    {error ? <span role="alert">{error}</span> : !quote ? uiText("加载中…") : <>
      <span className="mb-2 block text-xs text-muted-foreground">{quote.title} · {quote.start_line}–{quote.end_line}</span>
      <span className="block max-h-96 overflow-auto whitespace-pre-wrap break-words">{quote.text}</span>
      <span className="mt-2 flex gap-3 text-xs">
        <button type="button" onClick={() => void navigator.clipboard.writeText(quote.text).then(() => setCopied(true)).catch(e => setError(String(e)))}>{copied ? uiText("已复制") : uiText("复制")}</button>
        <a href={`/v1/files/${quote.file_id}/content?download=1`}>{uiText("下载")}</a>
      </span>
    </>}
  </span>;
}

export function ResourceReader({ id, media = false }: { id: string; media?: boolean }) {
  const [start, setStart] = useState(1);
  const [encoding, setEncoding] = useState("");
  const [data, setData] = useState<Awaited<ReturnType<typeof api.resourceText>>>();
  const [sources, setSources] = useState<Awaited<ReturnType<typeof api.resourceSources>>>([]);
  const [error, setError] = useState("");
  useEffect(() => { let active = true; void api.resourceSources(id).then(value => { if (active) setSources(value); }).catch(e => { if (active) setError(String(e)); }); return () => { active = false; }; }, [id]);
  useEffect(() => {
    if (media) return;
    let active = true; setData(undefined); setError("");
    void api.resourceText(id, start, encoding || undefined).then(value => { if (active) setData(value); }).catch(e => { if (active) setError(String(e)); });
    return () => { active = false; };
  }, [id, start, encoding, media]);
  return <div className="flex min-w-0 flex-col gap-3">
    <a className="text-sm underline" href={`/v1/files/${id}/content?download=1`}>{uiText("下载原件")}</a>
    {sources.map((source, index) => <a className="break-all text-xs underline" key={index} href={source.original_url} target="_blank" rel="noreferrer">{source.original_url}</a>)}
    {!media ? <><select aria-label={uiText("文本编码")} className="rounded border bg-background p-2" value={encoding} onChange={e => { setEncoding(e.target.value); setStart(1); }}>
      <option value="">UTF-8 / PDF / DOCX / EPUB</option><option value="gb18030">GB18030</option><option value="big5">Big5</option><option value="utf-16le">UTF-16 LE</option>
    </select>
    {error ? <p role="alert" className="text-sm text-destructive">{error}</p> : data ? <>
      <p className="text-xs text-muted-foreground">{start}–{data.next_line ? data.next_line - 1 : data.total_lines} / {data.total_lines}</p>
      <pre className="max-h-[60vh] overflow-auto whitespace-pre-wrap break-words text-sm">{data.text}</pre>
      <div className="flex gap-4"><button disabled={start === 1} onClick={() => setStart(Math.max(1, start - 200))}>{uiText("上一页")}</button><button disabled={!data.next_line} onClick={() => data.next_line && setStart(data.next_line)}>{uiText("下一页")}</button></div>
    </> : <p>{uiText("加载中…")}</p>}</> : error ? <p role="alert">{error}</p> : null}
  </div>;
}
